"use client"

/**
 * Temporarily neutralise CSS color functions that html2canvas cannot parse
 * (oklch, oklab, lab, lch — generated by Tailwind CSS v4).
 *
 * Two-pass approach:
 *   1. Override CSS custom properties on :root that resolve to modern color functions.
 *   2. Walk all DOM elements and inline-replace any computed color property that
 *      still contains oklch/oklab/lab/lch (Tailwind v4 utility classes generate
 *      these directly, not through CSS variables).
 */

const MODERN_COLOR_RE = /\b(oklch|oklab|lab|lch)\s*\(/

const COLOR_PROPS = [
  "color",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "outlineColor",
  "textDecorationColor",
  "fill",
  "stroke",
  "caretColor",
  "columnRuleColor",
] as const

/**
 * Resolve a modern color value to an rgb() string via a temporary element.
 * Falls back to a neutral gray if the browser cannot resolve.
 */
function resolveToRgb(value: string): string {
  const el = document.createElement("div")
  el.style.color = value
  document.body.appendChild(el)
  const rgb = getComputedStyle(el).color
  document.body.removeChild(el)
  return rgb && !MODERN_COLOR_RE.test(rgb) ? rgb : "rgb(107, 114, 128)" // gray-500 fallback
}

function patchUnsupportedColors(): () => void {
  const cleanups: (() => void)[] = []

  // ── Pass 1: Patch CSS custom properties on :root ──────────────────────
  const style = document.createElement("style")
  style.setAttribute("data-screenshot-patch", "true")

  const overrides: string[] = []
  const computed = getComputedStyle(document.documentElement)
  const rootStyles = document.documentElement.style

  const props = new Set<string>()
  for (const sheet of Array.from(document.styleSheets)) {
    try {
      for (const rule of Array.from(sheet.cssRules)) {
        if (rule instanceof CSSStyleRule && rule.selectorText === ":root") {
          for (let i = 0; i < rule.style.length; i++) {
            const p = rule.style[i]
            if (p.startsWith("--")) props.add(p)
          }
        }
      }
    } catch {
      // cross-origin sheets — skip
    }
  }
  for (let i = 0; i < rootStyles.length; i++) {
    const p = rootStyles[i]
    if (p.startsWith("--")) props.add(p)
  }

  for (const prop of props) {
    const val = computed.getPropertyValue(prop).trim()
    if (MODERN_COLOR_RE.test(val)) {
      const rgb = resolveToRgb(val)
      overrides.push(`${prop}: ${rgb};`)
    }
  }

  if (overrides.length > 0) {
    style.textContent = `:root { ${overrides.join(" ")} }`
    document.head.appendChild(style)
    cleanups.push(() => style.remove())
  }

  // ── Pass 2: Walk all elements and inline-patch computed colors ────────
  const savedStyles: { el: HTMLElement; prop: string; prev: string }[] = []

  const allElements = document.querySelectorAll("*")
  for (const node of Array.from(allElements)) {
    const el = node as HTMLElement
    if (!el.style) continue
    const cs = getComputedStyle(el)
    for (const prop of COLOR_PROPS) {
      const val = cs.getPropertyValue(
        prop.replace(/([A-Z])/g, "-$1").toLowerCase()
      )
      if (val && MODERN_COLOR_RE.test(val)) {
        savedStyles.push({ el, prop, prev: el.style.getPropertyValue(prop.replace(/([A-Z])/g, "-$1").toLowerCase()) })
        ;(el.style as unknown as Record<string, unknown>)[prop] = resolveToRgb(val)
      }
    }
  }

  cleanups.push(() => {
    for (const { el, prop, prev } of savedStyles) {
      if (prev) {
        ;(el.style as unknown as Record<string, unknown>)[prop] = prev
      } else {
        el.style.removeProperty(prop.replace(/([A-Z])/g, "-$1").toLowerCase())
      }
    }
  })

  return () => {
    for (const fn of cleanups) fn()
  }
}

export async function captureScreenshot(): Promise<{dataUrl: string | null; error: string | null}> {
  const removePatch = patchUnsupportedColors()
  try {
    const html2canvas = (await import("html2canvas")).default
    const canvas = await html2canvas(document.documentElement, {
      allowTaint: true,
      useCORS: true,
      scale: 0.6,
      logging: false,
      windowWidth: document.documentElement.scrollWidth,
      windowHeight: document.documentElement.scrollHeight,
      ignoreElements: (el) => {
        const tag = el.tagName?.toLowerCase()
        const type = (el as HTMLInputElement).type?.toLowerCase()
        const cls = String((el as HTMLElement).className || "")
        return (
          (tag === "input" && (type === "password" || type === "hidden")) ||
          cls.includes("sensitive") ||
          tag === "iframe"
        )
      },
    })
    return { dataUrl: canvas.toDataURL("image/jpeg", 0.75), error: null }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error("[screenshot] html2canvas failed:", msg)
    return { dataUrl: null, error: msg }
  } finally {
    removePatch()
  }
}

export async function uploadScreenshot(dataUrl: string): Promise<string | null> {
  try {
    const res = await fetch(dataUrl)
    const blob = await res.blob()
    const file = new File([blob], `debug-screenshot-${Date.now()}.jpg`, { type: "image/jpeg" })

    const form = new FormData()
    form.append("file", file)
    form.append("context", "debug-screenshot")

    const uploadRes = await fetch("/api/upload", {
      method: "POST",
      body: form,
    })

    if (!uploadRes.ok) return null
    const data = await uploadRes.json()
    return data.url || data.path || null
  } catch {
    return null
  }
}
