"use client"

/**
 * Temporarily neutralise CSS color functions that html2canvas cannot parse
 * (oklch, oklab, lab, lch — generated by Tailwind CSS v4).
 * Injects a <style> sheet that forces all custom-property colors to their
 * computed hex/rgb equivalents, then removes it after capture.
 */
function patchUnsupportedColors(): () => void {
  const style = document.createElement("style")
  style.setAttribute("data-screenshot-patch", "true")

  // Collect all CSS custom properties from :root that resolve to
  // modern color functions and override them with rgb() equivalents.
  const overrides: string[] = []
  const computed = getComputedStyle(document.documentElement)
  const rootStyles = document.documentElement.style

  // Walk registered custom properties from inline + sheets
  const props = new Set<string>()
  for (const sheet of Array.from(document.styleSheets)) {
    try {
      for (const rule of Array.from(sheet.cssRules)) {
        if (rule instanceof CSSStyleRule && rule.selectorText === ":root") {
          for (let i = 0; i < rule.style.length; i++) {
            const p = rule.style[i]
            if (p.startsWith("--")) props.add(p)
          }
        }
      }
    } catch {
      // cross-origin sheets — skip
    }
  }
  for (let i = 0; i < rootStyles.length; i++) {
    const p = rootStyles[i]
    if (p.startsWith("--")) props.add(p)
  }

  for (const prop of props) {
    const val = computed.getPropertyValue(prop).trim()
    if (/\b(oklch|oklab|lab|lch)\s*\(/.test(val)) {
      // Resolve to rgb via a temporary element
      const el = document.createElement("div")
      el.style.color = val
      document.body.appendChild(el)
      const rgb = getComputedStyle(el).color
      document.body.removeChild(el)
      if (rgb) overrides.push(`${prop}: ${rgb};`)
    }
  }

  if (overrides.length > 0) {
    style.textContent = `:root { ${overrides.join(" ")} }`
    document.head.appendChild(style)
  }

  return () => style.remove()
}

export async function captureScreenshot(): Promise<{dataUrl: string | null; error: string | null}> {
  const removePatch = patchUnsupportedColors()
  try {
    const html2canvas = (await import("html2canvas")).default
    const canvas = await html2canvas(document.documentElement, {
      allowTaint: true,
      useCORS: true,
      scale: 0.6,
      logging: false,
      windowWidth: document.documentElement.scrollWidth,
      windowHeight: document.documentElement.scrollHeight,
      ignoreElements: (el) => {
        const tag = el.tagName?.toLowerCase()
        const type = (el as HTMLInputElement).type?.toLowerCase()
        const cls = String((el as HTMLElement).className || "")
        return (
          (tag === "input" && (type === "password" || type === "hidden")) ||
          cls.includes("sensitive") ||
          tag === "iframe"
        )
      },
    })
    return { dataUrl: canvas.toDataURL("image/jpeg", 0.75), error: null }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error("[screenshot] html2canvas failed:", msg)
    return { dataUrl: null, error: msg }
  } finally {
    removePatch()
  }
}

export async function uploadScreenshot(dataUrl: string): Promise<string | null> {
  try {
    const res = await fetch(dataUrl)
    const blob = await res.blob()
    const file = new File([blob], `debug-screenshot-${Date.now()}.jpg`, { type: "image/jpeg" })

    const form = new FormData()
    form.append("file", file)
    form.append("context", "debug-screenshot")

    const uploadRes = await fetch("/api/upload", {
      method: "POST",
      body: form,
    })

    if (!uploadRes.ok) return null
    const data = await uploadRes.json()
    return data.url || data.path || null
  } catch {
    return null
  }
}
